# Generated by Django 2.1.5 on 2019-02-20 19:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('experiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cell_line', models.CharField(max_length=255)),
                ('treatment', models.CharField(max_length=255)),
                ('fileurl', models.FileField(max_length=255, upload_to='proteins/')),
                ('status', models.CharField(default='New', max_length=255)),
                ('published_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='ExperimentDetails1',
            new_name='ExperimentDetails',
        ),
        migrations.RenameModel(
            old_name='Experiment1',
            new_name='ExperimentName',
        ),
        migrations.DeleteModel(
            name='CustomExperiment1',
        ),
    ]
